### PR TITLE
Improve development workflow

### PR DESCRIPTION
**Pull request by miksask**
Hey,

Here are a few little improvements for the development workflow which, I think, might be helpful for those who might interested to add some features/fixes :-)

- Move dev dependencies from Travis config to separate file (so, we can do `pip install -r ...`)
- Determine versions of used packages for development (just in case, btw)
- Add coverage (might be useful for increasing stability)

### CODE REVIEW

**Comment by riscy** [comment]
Thanks!

**Comment by riscy** [comment]
I just realized this will break the Travis build for Python 2.7, since some of these aren't available on certain early versions of Python.  Will revisit soon.

**Comment by miksask** [comment]
oh, sorry… Just missed the 2.7 needs
I will fix it asap

**Comment by miksask** [comment]
added PR #7

**Pull request merged**
