### PR TITLE
Fix TravisCI builds for python 2.7

### PR DESCRIPTION
**Pull request by miksask**
fix a pylint versions range in requirements

### CODE REVIEW

**Comment by miksask** [comment]
@riscy, could you please review and merge this PR when you have a chance?

**Comment by riscy** [comment]
Hi, thanks for this.  I fixed Travis's authentication on the repository, so we should see build statuses coming up now.

The particular version of `coverage` appears to not work with Python 3.4.  3.4 is an _arbitrarily chosen_ earliest version of Python3 for which the tool appears to work.  Is it possible to fix the coverage version?  I won't be heartbroken if we have to take 3.4 out of the build matrix.

**Comment by miksask** [comment]
Hi, @riscy. Sorry for the late response, a lot of another activities…

I've added fixes for Python 3.4. Now all builds on TravisCI should pass.

However, Python 3.4 won't be maintained after March 2019 (cf PEP 429). So maybe in the future it might be not so necessary to support it here.

**Comment by riscy** [comment]
No worries, my attention is diffuse too. :)  I added Python 3.4 to the test suite simply because it happened to work -- not because I expected anyone to use it -- but I figure we might as well not drop it if we don't have to.

You are right, though - it may soon be time to look at modernizing the dependencies and dropping support for older Pythons.

**Comment by riscy** [comment]
And, thanks for this.  Looks great!

**Pull request merged**
